### ISSUE TITLE
Template error in tasks/main.yml

### ISSUE THREAD

**Issue by atleta** [FloeDesignTechnologies/ansible-exim4#1]
Hi,

In the last task (name: Create a catch all configuration) the jinja template string is wrong and causes the task to fail with a template error. It should be `exim4_catch_all_email is defined and exim4_catch_all_email is sameas false` instead of `exim4_catch_all_email is defined and exim4_catch_all_email is false`

  Cheers,
    Laszlo

**Comment by atleta** [comment]
Actually `exim4_catch_all_email is defined and not exim4_catch_all_email` works as well and is even better (for it works in case of supplying an empty string)

**Comment by PierrePaul** [comment]
Thanks for this.

**Comment by pbuyle** [comment]
I don't get it, `exim4_catch_all_email is defined and not exim4_catch_all_email` means the catch-all configuration file is only created if `exim4_catch_all_email` is defined and has a value coerced to `False`. So if `exim4_catch_all_email` is defined to an actual email adresss - a non-empty string -,  it will not be coerced to `False` and the file will not be created.

Wouldn’t the proper condition be `(exim4_catch_all_email is defined) and (exim4_catch_all_email)`?
